# 编译环境、语言
dist: xenial
os: linux
language: node_js

# Node.js 版本
node_js:
  - 14.15.5

branches:
  only:
    - hexo                      # 只有 master 分支检出更改才触发 CI

before_install:
  - export TZ='Asia/Shanghai'   # 配置时区为东八区 UTC+8
  - npm install hexo-cli        # 安装 hexo

install:
  - npm install                 # 安装 hexo 项目相关的依赖

# 执行脚本 
script:                         
  - hexo clean                  # 清除 hexo 缓存
  - hexo generate               # 生成静态文件
  - sed -i "s/xcbyao.github.io/${xcbyao.github.io}/g" ./_config.yml
  - hexo deploy

deploy:
  on:
    branch: hexo                # 工作分支
  strategy: git
  provider: pages
  #token: $xcbyao.github.io      # GitHub     Token 变量
  keep_history: true            # 保持推送记录，以增量提交的方式
