name: Deploy GitHub Pages
on:
  push:
    branches:
      - hexo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@xcbyao
        with:
          persist-credentials: false

      - name: Build
        run: npm install && npm run docs:build

      - name: Generate
        run: hexo clean && hexo g

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
          BRANCH: master
          FOLDER: docs/.vuepress/dist


